import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/theme-provider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Header from "@/components/Navbar/header";
import SideNavbar from "@/components/Navbar/SideNavbar";
import TextEffect from "@/components/ui/TextEffect";
import { TextHoverEffectDemo } from "@/components/TextEffect";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trajecta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId={process.env.AUTH_GOOGLE_ID || ""}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <SessionProvider>
              <div className="flex flex-col h-screen w-full ">
                <Header />
                <div className="w-full h-[90vh] flex flex-row   gap-5">
                  <SideNavbar />
                  <div className="w-full p-5">
                    
                    {children}
                  </div>
                </div>
              </div>
            </SessionProvider>
            <Toaster />
          </ThemeProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
